# Generated by Django 4.0.1 on 2022-01-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='codigo_status',
            new_name='status_id',
        ),
    ]
